apiVersion: v2
appVersion: "0.3.3"
description: A Helm chart for Socketkit Awacs
name: awacs
version: 0.1.4
type: application

dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
