apiVersion: v2
appVersion: "0.5.0"
description: A Helm chart for Socketkit Awacs
name: awacs
version: 0.2.0
type: application

dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
