replicaCount: 1

image:
  # -- default docker image
  repository: socketkit/awacs
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "awacs"
fullnameOverride: "awacs"

application:
  # -- default to true to run migration before every deployment
  autoMigrate: true
  config:
    NODE_ENV: "production"
    PGUSER: "postgres"
    PGPASSWORD: "postgres-password"
    PGDATABASE: "awacs"
    PGHOST: "awacs-postgresql"

postgresql:
  # -- attaches a postgresql instance to deployment
  enabled: false
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres-password"
  postgresqlDatabase: "awacs"
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "13.3.0-debian-10-r33"
  networkPolicy:
    enabled: false

pgchecker:
  image:
    repository: docker.io/busybox
    tag: 1.32
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  resources:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "10m"
      memory: "16Mi"

serviceAccount:
  # -- should create a service account
  create: true
  annotations: {}
  name: "awacs-account"

job:
  annotations: {}
  automountServiceAccountToken: true

service:
  public:
    type: ClusterIP
    # -- HTTP port
    port: 3002
  private:
    type: ClusterIP
    # -- gRPC port
    port: 4001

ingress:
  # -- default to false to not expose public api, should be true for most cases
  enabled: false
  annotations: {}
  hosts:
    - host: awacs.socketkit.com
  tls: []
   # - secretName: "awacs-tls"
   #   hosts:
   #     - awacs.socketkit.com

resources:
  limits: {}
    # cpu: 200m
    # memory: 256Mi
  requests: {}
    # cpu: 100m
    # memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

nodeSelector: {}

tolerations: []

affinity: {}
