apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.application.config }}
  {{ $k }}: {{ $v | b64enc}}
{{- end }}
