apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-private
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.private.type }}
  ports:
    - port: {{ .Values.service.private.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
