name: "Docs"

on:
  release:
    types:
      - published
  push:
    branches:
      - dev
      - main

jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "Deploy documentation"
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Install Protoc"
        uses: arduino/setup-protoc@v1

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: "Install protoc-gen-doc"
        run: |
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: "Generate Proto JSON"
        run: |
          protoc --doc_out=$GITHUB_WORKSPACE/docs/static --doc_opt=json,proto_workspace.json --proto_path=$GITHUB_WORKSPACE/src/protofiles $GITHUB_WORKSPACE/src/protofiles/**/*.proto

      - name: "Install dependencies"
        run: |
          npm ci

      - name: "Generate Proto Markdown"
        working-directory: "docs"
        run: |
          npm ci
          npm run scripts-generate
          npx docusaurus generate-proto-docs

      - name: "Deploy to Vercel"
        working-directory: "docs"
        run: |
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
