name: Publish

on:
  release:
    types: [published]

jobs:
  push_to_helm:
    name: Push as a Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.PUBLISH_BOT_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.socketkit.com
          owner: socketkit
          repository: awacs
          branch: helm-gh-pages
          commit_username: socketkit
          commit_email: hello@socketkit.com

  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository }}:${{ github.event.release.tag_name }}
            ${{ github.repository }}:latest

  push_to_github:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/awacs:${{ github.event.release.tag_name }}
            docker.pkg.github.com/${{ github.repository }}/awacs:latest

