name: Node Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: tracking
          POSTGRES_PASSWORD: tracking-password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -yq install libpq-dev postgresql-client-13

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Prepare Database & Users
        run: |
          npm ci
          npm run migrate
        env:
          PGDATABASE: tracking
          PGPASSWORD: tracking-password
          PGUSER: postgres
          PGHOST: localhost

      - name: Tests
        run: |
          npm run test:ci
        env:
          PGDATABASE: tracking
          PGUSER: postgres
          PGPASSWORD: tracking-password
          PGHOST: localhost

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
